services:
  linklet:
    #build: .
    image: ghcr.io/robertripoll/linklet
    container_name: linklet
    hostname: linklet
    ports:
      - "127.0.0.1:8002:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - DATA_FILE=/app/urls.json
      - VISITS_FILE=/app/visits.jsonl
    volumes:
      - ./urls.json:/app/urls.json
      - ./visits.jsonl:/app/visits.jsonl
      - ./blacklist.txt:/app/blacklist.txt
    restart: always
